### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by sturkmen72** [leonardvandriel/cvplot#1]
this will be a nice contribution if you think to contribute OpenCV library

**Comment by leovandriel** [comment]
Hi, thanks for suggesting. I didn't really think about doing that. Do you have any experience with contributing to OpenCV?

**Comment by sturkmen72** [comment]
yes, i can help on refactoring your code according to OpenCV's code style.

**Comment by leovandriel** [comment]
great. what changes do you think we need?

**Comment by sturkmen72** [comment]
I roughly looked at the code you wrote. for example some variable types can be converted to common OpenCV's variable types etc. Also probably OpenCV's core developers like @vpisarev and @alalek will guide us to better refactoring

**Comment by sturkmen72** [comment]
are you a student?

**Comment by leovandriel** [comment]
not student. I was working on some personal project with deep learning in caffe2 and wanted to plot some graphs of the training accuracy. I was surprised there was nothing decent available, so had a go myself.

About the variable types: yes, it would be good to use opencv internal formats. In this project i deliberately tried to avoid use of opencv names in headers, so it would only require opencv for linking.
