### ISSUE TITLE
Decouple from GLFW

### ISSUE THREAD

**Issue by PatJRobinson** [leonardvandriel/cvplot#40]
I really like this library and would like to use it in my project. However, its dependency on GLFW conflicts with the windowing system already being used with another dependency. 

I do not see any reason for this coupling - is there a way to simply render figure to an OpenCV image so that I can do what I want with it, without requiring GLFW create window function to be called?

Thanks in advance.

**Comment by PatJRobinson** [comment]
Closing - found a way around myself.

**Comment by PatJRobinson** [comment]
Closed - managed to solve myself. Basically, the windowing used in this library was conflicting with the windowing used by another, causing the program to crash. I made the following changes in window.cc and everything works fine for my purposes:

```
Window::Window(std::string title)
    : offset_(0, 0),
      title_(std::move(title)),
      cursor_(-10, -10),
      name_("cvplot_" + std::to_string(clock())) {
  // cv::namedWindow(name_, cv::WINDOW_AUTOSIZE);     // causes conflicts
  // cv::setMouseCallback(name_, mouse_callback, this);     // causes conflicts
}
```

**Comment by leovandriel** [comment]
Hi @PatJRobinson, thanks for sharing how you addressed the issue. I had not considered your usecase, but it makes sense to use cvplot without rendering to the screen.
