### ISSUE TITLE
demo crashes when run from build folder

### ISSUE THREAD

**Issue by jasonbeach** [leonardvandriel/cvplot#5]
`make demo` works as does running `./bin/demo` from the repo root directory.  However if I cd to the bin directory and .`/demo` the program crashes with the error:

`OpenCV Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /home/jason/mysource/opencv/modules/imgproc/src/resize.cpp, line 4044
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/jason/mysource/opencv/modules/imgproc/src/resize.cpp:4044: error: (-215) ssize.width > 0 && ssize.height > 0 in function resize`

Two small windows briefly appear but the larger demo one never does.  I will see  if I can figure anything out, but help would be great.  This is a great project by the way.

**Comment by jasonbeach** [comment]
I assume the problem is this line:
`auto image = cv::imread("res/demo.jpg");`

**Comment by leovandriel** [comment]
Thank you for reporting! Fixed in #31
